### ISSUE TITLE
Dependency not compatible with netcoreapp1.1

### ISSUE THREAD

**Issue by israelito3000** [ststeiger/Arsoft#1]
I received this error on compiling, maybe this reference can be upgraded?

Package System.Private.Networking 4.0.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win7-x86. Package System.Private.Networking 4.0.0 supports:
  - dnxcore50 (DNXCore,Version=v5.0)
  - netcore50 (.NETCore,Version=v5.0)

**Comment by ststeiger** [comment]
I will take a look at it.

**Comment by ststeiger** [comment]
There's no reference to System.Private.Networking anywhere in this repository. 
I also searched with AgentRansack, and didn't find anything. 
After Visual Studio 2017 updated the solution, it compiles fine. 
There was one little syntax error (missing brace) - don't know if I actually checked that in. 
Fixed that brace, and pushed the updated the project. 
Closing this issue. 
You should probably update to the latest .NET Core SDK.
